# CreateHostFromHostGroup.yml
# This play creates a host of a defined name from a defined hostgroup
- name: Publish and Promote the configured Content Views and Composite Content Views
  hosts: all
  vars_files:
  - vars/vault_all.yml
  - vars/smoketest_hostlist.yml

  tasks:
  - name: "Create the host"
    redhat.satellite.host:
      username: "{{ sat_publisher_username }}"
      password: "{{ sat_publisher_password }}"
      server_url: "{{ sat_server_url }}"
      name: "{{ host.fqdn }}"
      hostgroup: "{{ host.hostgroup }}"
      compute_profile: "{{ host.compute_profile"
      state: present
    loop: "{{ hostlist }}"
    loop_control:
      loop_var: host