# CreateHostFromHostGroup.yml
# This play creates a host of a defined name from a defined hostgroup
- name: Publish and Promote the configured Content Views and Composite Content Views
  hosts: all


  tasks:
  - name: "Create the host"
    include_tasks: tasks/test_reboot_baremetal.yml
      
    loop: "{{ hostlist }}"
    loop_control:
      loop_var: host
    


  # Don't assume the inventory_hostname is resolvable immediately
  # This is a long process so we can delay 300 seconds at start

  - name: Wait 1h for systems to come up on port 22 and contain "OpenSSH" - checking every 60s
    wait_for:
      timeout: 3600
      sleep: 60
      port: 22
      host: "{{ host.fqdn }}"
      search_regex: OpenSSH
      delay: 300
    connection: local
    loop: "{{ hostlist }}"
    loop_control:
      loop_var: host