sat_server_url: "https://sat6.parmstrong.ca"
organization: "Default Organization"
sat_publisher_username: "{{ vault_sat_publisher_username }}"
sat_publisher_password: "{{ vault_sat_publisher_password }}"
description: "Published by ansible-tower on {{ ansible_date_time.date }}"
filter_enddate: "{{ ansible_date_time.date }}"
num_cvs_to_keep: 3
content_views:
  - name: "RHEL7_SOE"
    date_filter_name: "ErrataByDate"
    environments:
    - "SOE_Development"
    - "SOE_Qualification"
    - "SOE_Production"
    - "App_Development"
  
  - name: "RHEL8_SOE"
    date_filter_name: "ErrataByDate"
    environments:
    - "SOE_Development"
    - "SOE_Qualification"
    - "SOE_Production"
    - "App_Development"
  
  - name: "UpgradeFromRHEL79"
    date_filter_name: "ErrataByDate"
    environments:
    - "SOE_Development"

  - name: "UpgradeToRHEL82"
    date_filter_name: "ErrataByDate"
    environments:
    - "SOE_Development"
    
  - name: "JBossEAP73"
    date_filter_name: "ErrataByDate"
    environments:
    - "SOE_Development"
    - "SOE_Qualification"
    - "SOE_Production"
    - "App_Development"
    
composite_content_views:
  - name: "RHEL79to82Upgrade"
    environments:
    - "SOE_Development"
    - "SOE_Qualification"
    - "SOE_Production"
    - "App_Development"
  
  - name: "JBoss_SOE"
    environments:
    - "SOE_Development"
    - "SOE_Qualification"
    - "SOE_Production"
    - "App_Development"

