---
# This task creates a composite content view from a definition suppied in all.yml
# This version of the ccvcreator assumes all filtering is done at the CV level 
# and that composites are unfiltered at this time
# TODO: move filter creation to a utility folder and allow filter creation to take place here as well.

- name: "Create the content view"
  redhat.satellite.content_view:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    organization: "{{ sat_organization }}"
    validate_certs: "{{ sat_validate_certs }}"
    name: "{{ cv.name }}"
    description: "{{ cv.desc }}"
    repositories: "{{ cv.repositories }}"
