---
# This role expects a list of content views as input. See sample variables in vars/all.yml
#

- name: Update the Errata-by-date filter for content views
  redhat.satellite.content_view_filter:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    name: "{{ item.date_filter_name}}"
    organization: "{{ sat_organization }}"
    content_view: "{{ item.name }}"
    description: "{{ description }}"
    filter_type: "erratum" # required for date filter
    date_type: "updated" # default
    end_date: "{{ filter_enddate }}"
    inclusion: True
  loop: "{{ content_views }}"

- name: Publish the new content view version
  redhat.satellite.content_view_version:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    content_view: "{{ item.name }}"
    organization: "{{ sat_organization }}"
    description: "{{ description }}"
  loop: "{{ content_views }}"

- name: Publish the new composite content views version
  redhat.satellite.content_view_version:
    username: "{{ sat_publisher_username }}"
    password: "{{ sat_publisher_password }}"
    server_url: "{{ sat_server_url }}"
    content_view: "{{ item.name }}"
    organization: "{{ sat_organization }}"
    description: "{{ description }}"
  loop: "{{ composite_content_views }}"


